spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      routes:
        - id: welcome-api
          uri: lb://HOME-API
          predicates:
            - Path=/home/**
        - id: greet-api
          uri: lb://ABOUT-US-API
          predicates:
            - Path=/about-us
  application:
    name: CLOUD-API-GATEWAY
server:
  port: 3333